# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest


steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'mis-recruitment-db/MIS.Services.Recruitment.Database.sln'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true

    
- task: SqlAzureDacpacDeployment@1
  inputs:
        azureSubscription: 'SantajiGCybage.OnMicrosoft.com'
        AuthenticationType: 'server'
        ServerName: 'cyb-mis-sql.database.windows.net'
        DatabaseName: 'mis-Finance-Db'
        SqlUsername: 'azsqladmin'
        SqlPassword: 'cybage@2011'
        deployType: 'DacpacTask'
        DeploymentAction: 'Publish'
        DacpacFile: 'MIS.Services.Recruitment.Database/bin/Debug/MIS.Services.Recruitment.Database.dacpac'
        IpDetectionMethod: 'AutoDetect'