trigger: 
- none
variables:
 - group: MIS-DB-RAVI
pool:
  vmImage: 'windows-latest'

resources:
  pipelines:
    - pipeline: Previous-pipeline-trigger
      source: MIS-TRAINING-DB1-DEPLOY
      trigger: true
      
  repositories:
    - repository: mis-reusable
      type: github
      name: cybagedevops/mis-reusable
      endpoint: mis
      ref: main

steps:
  - template: .azure/pipelines/ravi/Db-Template.yml@mis-reusable
    parameters:
     azureSubscription: $(azureSubscription)
     SqlServerName: $(SqlServerName)
     sqlLoginId: $(sqlLoginId)
     sqlPassword: $(sqlPassword)
     databaseName: 'Recruitment'
     azureDatabaseDbName: 'mis-Recruitment-Db'
