trigger: 
- none

variables:
 - group: MIS-DB-NILESH
pool:
   name: Azure VM Agent Pool

resources:
  # pipelines:
  #   - pipeline: Previous-pipeline-trigger
  #     source: MIS-DIGITAL-DB-DEPLOY
  #     trigger: true
  repositories:
    - repository: mis-reusable
      type: github
      name: cybagedevops/mis-reusable
      endpoint: mis
      ref: main
stages:
- stage: 'QA'
  jobs:
  - job: 'QA'
    steps:
      - template: .azure/pipelines/nilesh/Db-Template1.yml@mis-reusable
        parameters:
          azureSubscription: $(azureSubscription)
          azureSqlServerName:  $(SqlServerNameQA)
          azureSqlLoginName:  $(sqlLoginId)
          azureSqlPassword: $(sqlPassword)
          dbName: 'Recruitment'
          azureDbName: 'mis-recruitment-Db-nilesh-qa'
          artifactName: 'RecruitmentDB'
          buildDatabase: true
          copyDatabase: true
          publishDatabase: true
# - stage: 'Prod'
#   jobs:
#   - job: 'Prod'
#     steps:
#       - template: .azure/pipelines/nilesh/Db-Template1.yml@mis-reusable
#         parameters:
#           azureSubscription: $(azureSubscription)
#           azureSqlServerName:  $(SqlServerNameQA)
#           azureSqlLoginName:  $(sqlLoginId)
#           azureSqlPassword: $(sqlPassword)
#           dbName: 'Recruitment'
#           azureDbName: 'mis-recruitment-Db-nilesh-prod'  
#           artifactName: 'RecruitmentDB'
#           buildDatabase: false          
#           copyDatabase: false
#           publishDatabase: false   
