trigger: 
- none
variables:
  - group: LOCAL-DB-VAISHNAVI
pool:
  name: MIS Agent Pool
  demands:
    - agent.name -equals VAISHNAVIRA-VD3
 

resources:

  repositories:
    - repository: mis-reusable
      type: github
      name: cybagedevops/mis-reusable
      endpoint: mis
      ref: main

jobs:
  - template: .azure/pipelines/vaishnavi/MIS-REUSABLE-DB-IIS.yml@mis-reusable
    parameters:
      sqlServerName: $(sqlServerName)
      sqlAdmin: $(sqlAdmin)
      sqlPassword: $(sqlPassword)
      serviceName: 'Recruitment'
      dbName: 'mis-recruitment-db-vaishnavi'