trigger: 
- none

variables:
 - group: MIS-SQL-CREDENTIAL
# - group: MIS-AZURE
pool:
  name: Azure VM Agent Pool
  # demands:
  #  # - agent.name -equals VAISHNAVIRA-VD3
  #   - agent.name -equals Azure-VM-Agent-2
    
resources:
  pipelines:
     - pipeline: mis-project-db-vaishnavi
       source: MIS-PROJECT-DB-DEPLOY-VAISHNAVI
       trigger: true
  repositories:
    - repository: mis-reusable
      type: github
      name: cybagedevops/mis-reusable
      endpoint: mis
      ref: main
stages:
 - stage: 'QA'  
   jobs:
   - job: 'QA'
     variables:
      - group: MIS-SQL-SERVER-QA
     steps:
     
     - template: .azure/pipelines/vaishnavi/DB-TemplateQAProd.yml@mis-reusable
       parameters: 
        azureSubscription: 'SantajiGCybage.OnMicrosoft.com'
        SqlServerName: $(QAazureSqlServerName)
        sqlLoginId: $(azureSqlLoginName)
        sqlPassword: $(azureSqlPassword)
        azureDatabaseDbName: 'mis-recruitment-db-vaishnavi-qa'
        artifactName: 'RecruitmentDB'
        databaseName: 'Recruitment'
        buildDatabase: true
        copyDatabase: true
        publishDatabase: true
 
 
#  - stage: 'Production'
#    jobs:
#    - job: 'Production'
#      variables:
#         - group: MIS-SQL-SERVER-PROD
#      steps:
         
   
#      - template: .azure/pipelines/vaishnavi/DB-TemplateQAProd.yml@mis-reusable
#        parameters: 
#         azureSubscription: $(azureSubscription)
#         azureSQLServerName: $(QAazureSqlServerName)
#         azureSqlAdmin: $(azureSqlLoginName)
#         azureSqlPassword: $(azureSqlPassword)
#         azureDatabaseDbName: 'mis-recruitment-db-vaishnavi-prod'
#         artifactName: 'RecruitmentDB'
#         databaseName: 'Recruitment'
#         buildDatabase: true
#         copyDatabase: true
#         publishDatabase: true
        
        
 
 

 