trigger: 
- none

pool:
  name: MIS Agent Pool
  demands:
    - agent.name -equals VAISHNAVIRA-VD3
 

resources:

  repositories:
    - repository: mis-reusable
      type: github
      name: cybagedevops/mis-reusable
      endpoint: mis
      ref: main
variables:
 group: LOCAL-DB-VAISHNAVI

jobs:
  
  - template: .azure/pipelines/vaishnavi/MIS-REUSABLE-DB-IIS.yml@mis-reusable
    parameters:
       sqlServerName: 'VAISHNAVIRA-VD\SQL2017'
       sqlAdmin: 'sa'
       sqlPassword: 'cybage@123456'
       serviceName: 'Recruitment'
       dbName: 'mis-recruitment-db-vaishnavira'