trigger: 
- none

variables:
 - group: MIS-SQL-CREDENTIAL
 - group: MIS-AZURE
pool:
  name: Azure VM Agent Pool

resources:
  pipelines:
    - pipeline: Previous-pipeline-trigger
      source: MIS-TRAINING-DB1-DEPLOY
      trigger: true
  repositories:
    - repository: mis-reusable
      type: github
      name: cybagedevops/mis-reusable
      endpoint: mis
      ref: main
stages:
- stage: 'QA'
  jobs:
  - job: 'QA'
    variables:
      - group: MIS-SQL-SERVER-QA
    steps:
      - template: .azure/pipelines/ravi/Db-Template.yml@mis-reusable
        parameters:
          azureSubscription: $(azureSubscription)
          SqlServerName: $(QAazureSqlServerName)
          sqlLoginId: $(azureSqlLoginName)
          sqlPassword: $(azureSqlPassword)
          databaseName: 'Recruitment'
          azureDatabaseDbName: 'mis-Recruitment-Db-QA-ravi'
          artifactName: 'RecruitmentDB'
          buildDatabase: true
          copyDatabase: true
          publishDatabase: true

# - stage: 'Prod'
#   jobs:
#   - job: 'Prod'
#     variables:
#         - group: MIS-SQL-SERVER-PROD
#     steps:
#       - template: .azure/pipelines/ravi/Db-Template.yml@mis-reusable
#         parameters:
#           azureSubscription: $(azureSubscription)
#           SqlServerName: $(ProdazureSqlServerName)
#           sqlLoginId: $(azureSqlLoginName)
#           sqlPassword: $(azureSqlPassword)
#           databaseName: 'Recruitment'
#           azureDatabaseDbName: 'mis-Recruitment-Db-Prod-ravi' 
#           artifactName: 'RecruitmentDB'  
#           buildDatabase: false          
#           copyDatabase: false
#           publishDatabase: false     

