trigger: 
- none
variables:
  - group: LOCAL-DB-RAVI
pool:
  name: MIS Agent Pool
  demands:
    - agent.name -equals self-hosted-agent-Rk
 

resources:
  # pipelines:
  #   - pipeline: Previous-pipeline-trigger
  #     source: MIS-IAC-All-DB-DEPLOY
  #     trigger: true
  repositories:
    - repository: mis-reusable
      type: github
      name: cybagedevops/mis-reusable
      endpoint: mis
      ref: main

steps:
  - template: .azure/pipelines/ravi/DB-TEMPLATE-IIS-RK.yml@mis-reusable
    parameters:
     ServerName: $(ServerName)
     LoginId: $(LoginId)
     Password: $(Password)
     databaseName: 'Recruitment'