name: MIS-RECRUITMENT-DB-BUILD-DEPLOY-$(Year:yyyy).$(Month).$(DayOfMonth)-$(rev:rr)
 
pool: 
 name: Azure VM Agent Pool

resources:
  pipelines:
    - pipeline: iac-db-create-pipeline
      source: MIS-IAC-CREATE-DB-SHRIVIRAJ-20231101-01      
      trigger: true
  repositories:
    - repository: mis-reusable
      type: github
      name: cybagedevops/mis-reusable
      endpoint: mis
      ref: main

stages:
- stage: BuildAndPackage
  jobs:
  - job: BuildAndPackage
    steps:
     - template: .azure/shriviraj/build-deploy-db-template.yml@mis-reusable

- stage: 'QA'
  jobs: 
  - job: 'QA'
    steps:
    - task: UseDotNet@2
      inputs:
         packageType: 'sdk'
         version: '6.x'

    - task: DownloadPipelineArtifact@2
      inputs:
          buildType: 'current'
          artifactName: dacpac
          targetPath: '$(Build.ArtifactStagingDirectory)'

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |

              SqlPackage /Action:Publish /SourceFile:"$(Build.ArtifactStagingDirectory)/s/MIS.Services.Recruitment.Database\bin\Output\MIS.Services.Recruitment.Database.dacpac" /TargetConnectionString:"Server=$(QAazureSqlServerName).database.windows.net;Initial Catalog=mis-Recruitment-db-shriviraj-qa;Persist Security Info=False;User ID=$(azureSqlLoginName);Password= $(azureSqlPassword);MultipleActiveResultSets=False;Encrypt=False;TrustServerCertificate=True;Connection Timeout=30;" /p:DropObjectsNotInSource=true /p:AllowIncompatiblePlatform=true



# - stage: 'Prod'
#   jobs: 
#   - job: 'Prod-Approval'
#   - deployment: DeployToProdDeployment
#     displayName: 'Deploy to Prod'
#     environment: 'ShrivirajProd'
#     strategy:
#         runOnce:
#           deploy:
#             steps:
#             - task: UseDotNet@2
#               inputs:
#                      packageType: 'sdk'
#                      version: '6.x'

#             - task: DownloadPipelineArtifact@2
#               inputs:
#                   buildType: 'current'
#                   artifactName: dacpac
#                   targetPath: '$(Build.ArtifactStagingDirectory)'
#             - task: AzureCLI@2
#               inputs:
#                 azureSubscription: $(azureSubscription)
#                 scriptType: 'ps'
#                 scriptLocation: 'inlineScript'
#                 inlineScript: |
#                                 SqlPackage /Action:Publish /SourceFile:"$(Build.ArtifactStagingDirectory)/s/MIS.Services.Recruitment.Database\bin\Output\MIS.Services.Recruitment.Database.dacpac" /TargetConnectionString:"Server=$(ProdazureSqlServerName).database.windows.net;Initial Catalog=mis-Recruitment-db-shriviraj-prod;Persist Security Info=False;User ID=$(azureSqlLoginName);Password= $(azureSqlPassword);MultipleActiveResultSets=False;Encrypt=False;TrustServerCertificate=True;Connection Timeout=30;" /p:DropObjectsNotInSource=true /p:AllowIncompatiblePlatform=true
          