
trigger: 
- none
 
pool: 
 name: MIS Agent Pool
 demands:
    - agent.name -equals SHRIVIRAJA-VD3

resources:
   repositories:
    - repository: mis-reusable
      type: github
      name: cybagedevops/mis-reusable
      endpoint: mis
      ref: main

steps:
  - template: .azure/pipelines/shriviraj/LocalSqlDeployTemplate.yml@mis-reusable
    parameters:
     DbName: 'mis-recruitment-db-shriviraj'
     serviceName: 'Recruitment'