name: MIS-RECRUITMENT-DB-CREATE-BUILD-DEPLOY-LOCAL-YASH-$(Year:yyyy).$(Month).$(DayOfMonth)-$(rev:rr)

trigger:
- none

pool: 
 name: MIS Agent Pool
 demands:
    - agent.name -equals YASHDU-AGENT

resources:
 repositories:
   - repository: mis-reusable
     type: github
     name: cybagedevops/mis-reusable
     endpoint: mis
     ref: main
variables:
 group: mis-yash-local
jobs:
 - template: .azure/pipelines/yash/create-build-deploy-db-reusable-yash-local-01.yml@mis-reusable
   parameters:
     sqlServerName: $(sqlServerName)
     sqlAdmin: $(sqlAdmin)
     sqlPassword: $(sqlPassword)
     serviceName: 'Recruitment'
     dbName: 'mis-recruitment-db-yash'