name: MIS-RECRUITMENT-DB-CREATE-BUILD-DEPLOY-$(Year:yyyy).$(Month).$(DayOfMonth)-$(rev:rr)

trigger:
- none

pool: 
 name: Azure VM Agent Pool

resources:
  # pipelines:
  #     - pipeline: mis-project-db-yash
  #       source: MIS-PROJECT-DB-CI-CD-YASH-20231107-01
  #       trigger: true

  repositories:
    - repository: mis-reusable
      type: github
      name: cybagedevops/mis-reusable
      endpoint: mis
      ref: main
variables:
 group: MIS-DB-YASH

jobs:
 - template: .azure/create-build-deploy-db-reusable.yml@mis-reusable
   parameters: 
        azureSubscription: $(azureSubscription)
        azureSQLServerName: $(azureSQLServerName)
        azureSqlAdmin: $(azureSqlAdmin)
        azureSqlPassword: $(azureSqlPassword)
        elasticPoolName: $(elasticPoolName)
        azuredbName: 'mis-recruitment-db-yash'
        artifactName: 'RecruitmentDB'
        serviceName: 'Recruitment'